license="MIT"
modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory
issueTrackerURL="https://github.com/CodenameRevy/AdditionalBars/issues" #optional

[[mods]] #mandatory
modId="additionalbars" #mandatory
version="4.0.0" #mandatory
displayName="Additional Bars" #mandatory
displayURL="gamma1772.github.io" #optional
logoFile="logo.png" #optional
credits='''Gamma1772 (Mod Developer), ruchom4u (Spanish Translations), fantasyair18 (Chinese Traditional (Taiwan) Translations), TheDirectorX, BardinTheDwarf (Russian Translations), Zijuna (German Translations), justmonika (Simple Chinese Translations), mindy15963 (Korean Translations), WadeMason''' #optional
authors="Gamma1772" #optional
description='''
This mod adds additional bars to the game that go along with Iron Bars!
'''

[[dependencies.additionalbars]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.additionalbars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"